### ISSUE TITLE
[7.0] Incompatibility between account_statement_ext and account_banking

### ISSUE THREAD

**Issue by ecino** [OCA/account-reconcile#37] opened 2014-08-18 06:42 UTC
I cannot install the module account_statement_ext together with the account_banking module, because both modules replace the field period_id in the view account.view_bank_statement_tree.

**Comment by alexis-via** [comment] 2014-10-13 09:24
This is a know issue. But you should not need the module account_banking if you use account_statement_ext: in the banking branch, you should only need account_banking_payment_export.

**Comment by ecino** [comment] 2014-10-14 08:01
Thanks for the tip. In fact I need the account_banking module because it is a dependency of module account_payment which I use for having filters on payment terms in direct debit orders.

**Comment by sbidoul** [comment] 2014-10-14 18:20
@ecino account_banking_payment will soon be independent of account_banking.

In this 8.0 branch https://github.com/acsone/banking/tree/8.0-refactor-account_banking_payment-sbi, the module is split in account_banking_payment_transfer and account_banking_payment_term.

**Comment by alexis-via** [comment] 2014-10-14 21:35
@sbidoul 
Great news ! I just had some trouble today because I thought that account_banking_payment was already independant from account_banking, so I uninstalled account_banking, and it silently uninstalled account_banking_payment (I hate the silent uninstalll of dependancies on Openerp v7 ; hopefully, this is fixed in v8) and several other custom modules ! In fact, the only usefull feature for me in account_banking_payment is the addition of the transfer account and transfer journal on the payment.mode and the fact that it creates accounting entries when the payment order is validated. This is a really important feature.

**Comment by sbidoul** [comment] 2014-10-15 06:17
@alexis-via my branch is built on top of Pedro's 8.0 port. I'd really appreciate if you could test it, especially wrt direct debit.

**Comment by RoelAdriaans** [comment] 2014-10-15 19:44
We use account_banking because we need it for account_banking_camt for importing the bank files. 

With account_banking and account_statement_ext installed, statement lines without a invoice are no longer set to confirmed. This is a problem when a statement is canceled and confirmed again, because the account move lines are created again, creating duplicate accounting entries.

**Comment by sbidoul** [comment] 2014-10-15 20:34
@RoelAdriaans-B-informed in 7.0, any module of OCA/banking that depends on account_banking is incompatible with OCA/bank-statement-reconcile. There is no known way to solve this in the 7.0 branches. 

The plan for 8.0 is discussed in this thread: https://lists.launchpad.net/banking-addons-drivers/msg00120.html

**Comment by bwrsandman** [comment] 2015-01-23 19:46
What's the status on this issue? Can it be closed?

**Comment by pedrobaeza** [comment] 2015-01-23 19:49
I think so, because with the new account_statement_import framework, there is no possible incompatibility.

**Closed as completed** 2015-02-20 19:30 UTC
