### ISSUE TITLE
[12.0][BUG] account_skip_bank_reconciliation?

### ISSUE THREAD

**Issue by alexey-pelykh** [OCA/account-reconcile#335] opened 2020-09-06 07:31 UTC
On runbot, create Reconciliation Model:
![image](https://user-images.githubusercontent.com/345102/92320712-bafebe00-f023-11ea-947f-40728d4a1bf6.png)
![image](https://user-images.githubusercontent.com/345102/92320716-c356f900-f023-11ea-8f9b-2c8368a482e9.png)

Open reconcile mode, and observe:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/OCB-12.0/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 755, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 728, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/OCB-12.0/addons/account/models/reconciliation_widget.py", line 210, in get_bank_statement_data
    results = self.get_bank_statement_line_data(bank_statement_lines.ids)
  File "/home/odoo/build/OCA/account-reconcile/account_reconcile_payment_order/models/account_reconciliation_widget.py", line 55, in get_bank_statement_line_data
    st_line_ids, excluded_ids=excluded_ids,
  File "/home/odoo/OCB-12.0/addons/account/models/reconciliation_widget.py", line 148, in get_bank_statement_line_data
    matching_amls = reconcile_model._apply_rules(bank_statement_lines, excluded_ids=excluded_ids, partner_map=partner_map)
  File "/home/odoo/OCB-12.0/addons/account/models/account_reconcile_model.py", line 624, in _apply_rules
    self._cr.execute(query, params)
  File "/.repo_requirements/odoo/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: missing FROM-clause entry for table "account"
LINE 20: ...id IN (7) AND st_line.name ILIKE '%Bank Fee%' AND account.ex...
                                                              ^
```

**Comment by alexey-pelykh** [comment] 2020-09-19 07:24
Uninstalling `account_skip_bank_reconciliation` resolves the issue. Thus cc @MiquelRForgeFlow @AdriaGForgeFlow

**Comment by MiquelRForgeFlow** [comment] 2020-09-21 07:50
It's strange your error because it says "account" is missing, but it really exists in https://github.com/odoo/odoo/blob/12.0/addons/account/models/account_reconcile_model.py#L424.

**Comment by alexey-pelykh** [comment] 2020-09-21 07:54
Well, it is reproducible on runbot easily. Right now this bug makes runbot unusable unless module is uninstalled

**Comment by MiquelRForgeFlow** [comment] 2020-09-21 07:58
Yeah, I found the cause. The _apply_conditions method is also called in https://github.com/odoo/odoo/blob/12.0/addons/account/models/account_reconcile_model.py#L523, which this one doesn't have "account" :(

**Comment by MiquelRForgeFlow** [comment] 2020-09-21 08:24
Fixed in https://github.com/OCA/account-reconcile/pull/341.

**Closed as completed** 2020-09-21 08:42 UTC
