### ISSUE TITLE
[16] Manual reconciliation with write-off is not allowed on accounting entries where period journal is locked

### ISSUE THREAD

**Issue by medinisa** [OCA/account-reconcile#712] opened 2024-09-27 12:58 UTC
Hello, 

We know that it is possible to reconcile items recorded in locked periods. In fact, it works with the reconciliation module, but it does not work with manual reconciliation. Is it possible to fix this issue? It is related to the module account_journal_lock_date.

![reconcile issue](https://github.com/user-attachments/assets/feb17e9b-f82e-4225-9695-22ed2f6eb4db)

## Module
account_move_line_reconcile_manual, account_journal_lock_date.

## To Reproduce
Odoo version 16

Ensure current period is not locked in journals

1. Accounting - Journals - Journal items
2. Select items to reconcile
3.Reconcile with WRITE-OFF
4.Fill necessary fields
5.Validate

**Comment by medinisa** [comment] 2024-10-14 10:14
Hello, could you please help with this?

**Comment by pedrobaeza** [comment] 2024-10-14 11:15
That's something correct, as you can't modify journal items in the locked period. When only reconciling 2 entries already booked, there's no accounting modification.

Closing as no issue, but expected behavior.

**Closed as completed by pedrobaeza** 2024-10-14 11:15 UTC
Labels: bug

**Comment by medinisa** [comment] 2024-10-14 11:21
Sorry to insist, since I have a lot of experience in accounting and I use many ERPs, reconciliation is meant to match old entries, even if the period in which they were recorded is closed. This is wotking for classic reconcile as quoted

**Comment by pedrobaeza** [comment] 2024-10-14 11:23
A write-off means a different journal entry, so you are trying to modify things, so it's forbidden by the other module.

**Comment by medinisa** [comment] 2024-10-14 11:26
Exact, and The different journal entry is not locked in current period, but still blocking the operation

**Comment by pedrobaeza** [comment] 2024-10-14 11:28
It's posted on the date of the lines, not as a new entry in today date. Maybe this is what you are expecting, but that can't be.

**Comment by medinisa** [comment] 2024-10-14 11:31
> It's posted on the date of the lines, not as a new entry in today date. Maybe this is what you are expecting, but that can't be.

I've chosen the current date which is not locked.

**Comment by medinisa** [comment] 2024-10-14 11:36
And it's normal in reconciliation (allowed to change somes fields like full_reconcile_id, matching_number, amount_residual...) even if the entry is closed

**Comment by medinisa** [comment] 2024-10-15 20:46
I will pay an developper to make this change since reconciliation for old entries should be possible in any accounting system. Thank you anyway

**Comment by florian-dacosta** [comment] 2024-10-16 16:03
Hello, this is strange indeed, but is it a reconciliation in foreign currency (currency different than company currency ) ?
Because I see the write off is made in "Différence de change" journal, and it seems weird.
Indeed, in Odoo, the exchange rate difference are done automatically by the system, you should probably not do a manual write-off about it.

Hard to tell if this is the issue without having all the details, but I believe it is a part of the problem.

Also, this module does not work fine with mult-currency in its current state. I have made a pull request to fix the manual reconciliation in a foreign currency some time ago, but it is not yet merged : https://github.com/OCA/account-reconcile/pull/660

@medinisa Could you test your case after updating the module with the above PR?
If it solves the case, I guess you could approve it. Else, you could give more details about your case : 
- What is the company currency ?
- What are the amount and currency of the accounting entries you want to reconcile ? (amount in foreign currency + debit/credit)

I made a quick test anyway with `account_journal_lock_date` module installed, and I had not issue for a company currency reconciliation.

**Comment by medinisa** [comment] 2024-10-16 18:27
Hello, thank you for your answer @florian-dacosta, 

You are right the, one of the entry I want to reconcile is in Euro (company in CFA), but the amount is converted and the difference is only 0,47 CFA ( amount to write-off), it's only a rounding difference. So , I updated the module with the PR not yet merged and made a test, I'm getting the same message error : 
Please find below test I made : 

- Lines to reconcile  : 
![image](https://github.com/user-attachments/assets/58b06fb9-9b7a-441e-bb1f-e48baa1f9afa)

- Reconcile parameters  :  Journal is not important, I got the same message with another journal.
![image](https://github.com/user-attachments/assets/5ec712ba-ccda-4d9b-967d-d9c7f75ecff8)

- Error message
![image](https://github.com/user-attachments/assets/56359e8e-5913-4e50-865a-8f35b439ff15)


Journals of current period are not locked : 

![image](https://github.com/user-attachments/assets/52c0bc2d-3308-48a0-9bf6-6b994fc59203).

- I made a test after changing and set 2019-01-01 as lock date for all journals, since the invoice is booked on february 2024 and the paiement on august 2024, I got another message error : 
![image](https://github.com/user-attachments/assets/211a3464-47da-46cc-9b6d-f5b046333c2c)

Mayebe something to review in account_journal_lock_date ?

Thanks & regards

Samir

**Comment by medinisa** [comment] 2024-10-16 18:40
As you said before, the change difference is set automatically, 

![image](https://github.com/user-attachments/assets/697f37d4-8f76-4a50-9dd5-bfb1f10fcc10)
But we still need to find a solution. In fact, in some cases, we book the difference in difference of payment (same currency for invoice / payment).

**Comment by florian-dacosta** [comment] 2024-10-16 20:43
Well, I believe, there are actually 2 issues.
1) In `account_journal_lock_date`. Like we said, Odoo creates exchange rate entries automatically. When it does, it check the accounting lock date, at company level. (these lock dates are in native `account` module). If the date of the exchange entry is in a lock period, Odoo will automatically adapt the date and set the lock date +1.
Example : Odoo want to creates an exchange rate entry for the 15/09/2023. The fiscalyear lock date is set at 31/12/2023. Odoo will change the date of the exchange entry to 01/01/2024. This to avoid an blocking error message.
But, there are no such logic in `account_journal_lock_date`. So when Odoo tries to adapt the date, it does not consider the lock date of the journal, that is why it may fail.
@pedrobaeza FYI

Here where Odoo tries to find the right date : https://github.com/odoo/odoo/blob/16.0/addons/account/models/account_move_line.py#L2069
Here the method that is not but somehow should be overrided in `account_journal_lock_date` : https://github.com/odoo/odoo/blob/16.0/addons/account/models/company.py#L366

2) The is a known issue in `account_move_line_reconcile_manual`, you can't really reconcile entries in 2 different currencies. Or at least, it has a big probability of blocking with the message you had.
https://github.com/akretion/account-reconcile/blob/16-reconcile-manual-multi-currency/account_move_line_reconcile_manual/ROADMAP.rst
=> I did try to fix this one, but the way Odoo does the multi currency reconciliation is kind of a mess, and I could not fix this case.
The module work for reconciliation of entries having a same single currency (company currency, or foreign currency).
But entries with multiple different currencies does not work.

**Comment by medinisa** [comment] 2024-10-17 08:10
Thank you very much, I will ask users to change the way they record the payment, it should be done with the same currency as the invoice.
